name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json/')}}
          restore-key: |
            ${{runner.os}}-node-
      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      - run: npm install
      - name: build projects
        if: github.event_name == 'push'
        run: |
          node -v