name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      - run: npm ci    #install dependency
      # - run: npm run format:check    check code formatting
      - run: npm test -- --coverage    #run automate test